name: build-version


on:
  workflow_dispatch:
    inputs:
      kafka-version:
        description: "Kafka version"
        required: true
        default: '2.6.0'
      scala-version:
        description: 'Scala version'
        required: true
        default: '2.13'
      docker-tag:
        description: 'Tag of the docker image'
        required: true
        default: '2.13-2.6.0'

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.x'
      - name: install pipenv
        run: python -m pip install pipenv
      - uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-python-3.7-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-3.7-
      - name: Install python test dependencies
        run: make install
      - name: Run tests
        run: make test
        env:
          KAFKA_VERSION: ${{ github.event.inputs.kafka-version }}
          SCALA_VERSION: ${{ github.event.inputs.scala-version }}
      - name: Push to dockerhub
        run: make build-and-push
        env:
          KAFKA_VERSION: ${{ github.event.inputs.kafka-version }}
          SCALA_VERSION: ${{ github.event.inputs.scala-version }}
          DOCKER_TAG: ${{ github.event.inputs.docker-tag }}