name: ci-tests

on: push

jobs:
  test-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        kafka-version: ["2.2.1", "2.4.0", "2.6.0"]

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.x'
      - name: install pipenv
        run: python -m pip install pipenv
      - uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-python-3.7-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-3.7-
      - name: Install python test dependencies
        run: make install
      - name: Run tests
        run: make test
        env:
          KAFKA_VERSION: ${{ matrix.kafka-version }}